// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about-us" | "/admin" | "/admin/login" | "/blog" | "/blog/[slug]" | "/brochure" | "/careers" | "/contact-us" | "/en-in/industries/[slug]" | "/en-in/industries/[slug]/[productSlug]" | "/en-in/industries/[slug]/[productSlug]/[modelSlug]" | "/en-in/products" | "/en-in/products/[slug]" | "/en-in/products/[slug]/[modelSlug]" | "/faqs" | "/find-a-dealer" | "/hire-rental-industry-equipment" | "/industries/[slug]" | "/industries/[slug]/[productSlug]" | "/industries/[slug]/[productSlug]/[modelSlug]" | "/privacy-policy" | "/product/[slug]" | "/products" | "/products/[slug]" | "/products/[slug]/[modelSlug]" | "/terms-and-conditions" | "/videos"
type AppRouteHandlerRoutes = "/api/auth" | "/api/blogs" | "/api/blogs/[id]" | "/api/dealers" | "/api/dealers/[id]" | "/api/hero-section" | "/api/hero-section/[id]" | "/api/industries" | "/api/industries-with-products" | "/api/industries/[id]" | "/api/models" | "/api/models/[id]" | "/api/products" | "/api/products-with-models" | "/api/products/[id]" | "/api/submit-lead" | "/api/videos" | "/api/videos/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about-us": {}
  "/admin": {}
  "/admin/login": {}
  "/api/auth": {}
  "/api/blogs": {}
  "/api/blogs/[id]": { "id": string; }
  "/api/dealers": {}
  "/api/dealers/[id]": { "id": string; }
  "/api/hero-section": {}
  "/api/hero-section/[id]": { "id": string; }
  "/api/industries": {}
  "/api/industries-with-products": {}
  "/api/industries/[id]": { "id": string; }
  "/api/models": {}
  "/api/models/[id]": { "id": string; }
  "/api/products": {}
  "/api/products-with-models": {}
  "/api/products/[id]": { "id": string; }
  "/api/submit-lead": {}
  "/api/videos": {}
  "/api/videos/[id]": { "id": string; }
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/brochure": {}
  "/careers": {}
  "/contact-us": {}
  "/en-in/industries/[slug]": { "slug": string; }
  "/en-in/industries/[slug]/[productSlug]": { "slug": string; "productSlug": string; }
  "/en-in/industries/[slug]/[productSlug]/[modelSlug]": { "slug": string; "productSlug": string; "modelSlug": string; }
  "/en-in/products": {}
  "/en-in/products/[slug]": { "slug": string; }
  "/en-in/products/[slug]/[modelSlug]": { "slug": string; "modelSlug": string; }
  "/faqs": {}
  "/find-a-dealer": {}
  "/hire-rental-industry-equipment": {}
  "/industries/[slug]": { "slug": string; }
  "/industries/[slug]/[productSlug]": { "slug": string; "productSlug": string; }
  "/industries/[slug]/[productSlug]/[modelSlug]": { "slug": string; "productSlug": string; "modelSlug": string; }
  "/privacy-policy": {}
  "/product/[slug]": { "slug": string; }
  "/products": {}
  "/products/[slug]": { "slug": string; }
  "/products/[slug]/[modelSlug]": { "slug": string; "modelSlug": string; }
  "/terms-and-conditions": {}
  "/videos": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
